# Generated by Django 4.0.4 on 2022-05-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0002_rename_postmodel_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Publicacao',
        ),
    ]
