# Generated by Django 4.0.4 on 2022-05-12 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_delete_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
