# Generated by Django 4.0.4 on 2022-05-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_data',
            new_name='post_date',
        ),
    ]
